---
version: "2"
plugins:
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/EvalExpression:
        enabled: false
      UnusedFormalParameter:
        enabled: false
  phpcodesniffer:
    enabled: true
  sonar-php:
    enabled: true
  phan:
    enabled: true
exclude_patterns:
- 'tests/'
