---
engines:
  duplication:
    enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/EvalExpression:
        enabled: false
      UnusedFormalParameter:
        enabled: false
plugins:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  SonarPHP:
    enabled: true
  phan:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- tests/
